import type { NextPage } from "next";
import Head from "next/head";
import { ThemeProvider } from "styled-components";
import theme from "theme";
import { Modal } from "components";
import { GlobalStyle } from "theme/GlobalStyle";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <Modal isVisible />
      </ThemeProvider>
    </div>
  );
};

export default Home;
