import type { NextPage } from "next";
import Head from "next/head";
import { ThemeProvider } from "styled-components";
import theme from "theme";
import { Modal, Footer, PlusButton } from "components";
import { GlobalStyle } from "theme/GlobalStyle";
import styled from "styled-components";
import { useDispatch } from "react-redux";
import { openModal } from "redux/reducers/modal/modal.reducer";

const Container = styled.main`
  flex: 1;
  display: flex;
  flex-wrap: wrap;
  flex-direction: column;
  justify-content: space-between;
`;

const Tasks = styled.aside`
  padding: 10px;
`;

const Home: NextPage = () => {
  const dispatch = useDispatch();

  const openingModal = () => {
    dispatch(openModal());
  };

  return (
    <Container>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <Modal />
        <Tasks>
          <h1>Opa, parece que não há tarefas criadas</h1>
        </Tasks>
        <PlusButton onClick={openingModal} />
        <Footer />
      </ThemeProvider>
    </Container>
  );
};

export default Home;
